"""Launch-at-startup management (Windows).

Implemented as a tiny ``.vbs`` script in the user's Startup folder — the same
mechanism ``setup.ps1 -Autostart`` uses. Compared to a registry Run key it is
transparent (visible in ``shell:startup``), trivially removable, and the VBS
wrapper launches the widget without a console-window flash.

The *existence of the file* is the single source of truth — there is no config
flag to drift out of sync with reality. The menu checkbox simply reflects
:func:`is_enabled` at the moment the menu opens.
"""

from __future__ import annotations

import os
import shutil
import sys

_SCRIPT_NAME = "claude-usage-widget.vbs"


def _startup_dir() -> str:
    """The per-user Startup folder (``shell:startup``)."""
    appdata = os.environ.get("APPDATA") or os.path.expanduser("~\\AppData\\Roaming")
    return os.path.join(appdata, "Microsoft", "Windows", "Start Menu", "Programs", "Startup")


def _script_path(startup_dir: str | None = None) -> str:
    return os.path.join(startup_dir or _startup_dir(), _SCRIPT_NAME)


def _exe_path() -> str | None:
    """Locate the installed ``claude-usage`` executable."""
    found = shutil.which("claude-usage")
    if found:
        return found
    candidate = os.path.expanduser("~\\.local\\bin\\claude-usage.exe")
    return candidate if os.path.isfile(candidate) else None


def is_enabled(startup_dir: str | None = None) -> bool:
    """True if the launch-at-startup script is present."""
    return os.path.isfile(_script_path(startup_dir))


def enable(startup_dir: str | None = None) -> bool:
    """Create the Startup-folder launcher. Returns True on success."""
    if sys.platform != "win32" and startup_dir is None:
        return False
    exe = _exe_path()
    if not exe:
        return False
    path = _script_path(startup_dir)
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        # VBS must be plain ANSI/ASCII — a UTF-8 BOM breaks the script host.
        with open(path, "w", encoding="ascii", errors="replace", newline="\r\n") as f:
            f.write(
                "' Auto-generated by Claude Usage Widget - launches the OSD hidden at login.\n"
                "' Delete this file (or toggle 'Launch at startup' in the widget menu) to disable.\n"
                f'CreateObject("WScript.Shell").Run """{exe}""", 0, False\n'
            )
        return True
    except OSError:
        return False


def disable(startup_dir: str | None = None) -> bool:
    """Remove the Startup-folder launcher. Returns True if absent afterwards."""
    path = _script_path(startup_dir)
    try:
        if os.path.isfile(path):
            os.remove(path)
        return True
    except OSError:
        return False


def set_enabled(enabled: bool, startup_dir: str | None = None) -> bool:
    """Enable or disable launch-at-startup; returns True on success."""
    return enable(startup_dir) if enabled else disable(startup_dir)
